services:
  testkit:
    depends_on:
      redis_test:
        condition: service_healthy
  testkit-browser:
    depends_on:
      redis_test:
        condition: service_healthy

  redis_test:
    image: redis:7-alpine
    command:
      - redis-server
      - --save
      - ""
      - --appendonly
      - "no"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30
